version: '3.7'

services:
  test-app:
    depends_on:
      - test-db
    build:
      context: .
      dockerfile: testing-Dockerfile
    environment:
      - DATABASE_HOST=test-db

  test-db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=vapor_test
      - POSTGRES_USER=vapor_username
      - POSTGRES_PASSWORD=vapor_password
    ports:
      - '5432:5432'
