version: '3.7'

services:
  sf-app-tests:
    depends_on:
      - postgres_test
    build:
      context: .
      dockerfile: testing-Dockerfile
    environment:
      - DATABASE_HOST=postgres_test

  postgres_test:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=vapor_test
      - POSTGRES_USER=vapor_username
      - POSTGRES_PASSWORD=vapor_password
    ports:
      - '5432:5432'
